import * as React from 'react';
import { ArrowUpLeft, Download, MoreHorizontal, Plus, Search, Settings2, SlidersHorizontal } from 'lucide-react';
import { Button, TextField, Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter, DialogClose, DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuSub, DropdownMenuSubTrigger, DropdownMenuSubContent, DropdownMenuPortal, Select, SelectTrigger, SelectValue, SelectContent, SelectItem, Popover, PopoverTrigger, PopoverContent, Sheet, SheetTrigger, SheetContent, SheetHeader, SheetTitle, SheetDescription, Tabs, TabsList, TabsTrigger, TabsContent, Switch, Checkbox, Label, Tooltip, TooltipProvider, TooltipTrigger, TooltipContent, Accordion, AccordionItem, AccordionTrigger, AccordionContent, AlertDialog, AlertDialogTrigger, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction, StatusBadge, DataTable, EmptyState, ErrorState, LoadingState, Card, CardHeader, CardTitle, CardDescription, CardContent, Textarea } from '@toptech/ui';

export function ProjectMenu({ onChoose = () => {}, label = 'إجراءات المشروع' }: { onChoose?: (value: string) => void; label?: string }) {
  return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" aria-label={label}><MoreHorizontal size={18}/><span>{label}</span></Button></DropdownMenuTrigger><DropdownMenuContent align="start" className="w-64"><DropdownMenuLabel>المشروع الحالي</DropdownMenuLabel><DropdownMenuSeparator/><DropdownMenuItem onSelect={() => onChoose('تم تنزيل التقرير')}><Download/>تنزيل التقرير</DropdownMenuItem><DropdownMenuItem onSelect={() => onChoose('تم فتح إعدادات المشروع')}><Settings2/>إعدادات المشروع</DropdownMenuItem><DropdownMenuSub><DropdownMenuSubTrigger>مشاركة مع الفريق</DropdownMenuSubTrigger><DropdownMenuPortal><DropdownMenuSubContent collisionPadding={16}><DropdownMenuItem onSelect={() => onChoose('تم اختيار صلاحية القراءة')}>للقراءة فقط</DropdownMenuItem><DropdownMenuItem onSelect={() => onChoose('تم اختيار صلاحية التحرير')}>للقراءة والتحرير</DropdownMenuItem></DropdownMenuSubContent></DropdownMenuPortal></DropdownMenuSub><DropdownMenuSeparator/><DropdownMenuItem disabled>الأرشفة غير متاحة</DropdownMenuItem></DropdownMenuContent></DropdownMenu>;
}
export function RegionSelect({ id = 'region' }: { id?: string }) {
  return <div className="tt-field"><Label htmlFor={id}>المنطقة</Label><Select defaultValue="riyadh"><SelectTrigger id={id}><SelectValue placeholder="اختر المنطقة"/></SelectTrigger><SelectContent><SelectItem value="riyadh">منطقة الرياض</SelectItem><SelectItem value="makkah">منطقة مكة المكرمة</SelectItem><SelectItem value="eastern">المنطقة الشرقية</SelectItem><SelectItem value="long">منطقة ذات اسم عربي طويل لا ينبغي أن يتجاوز حدود شاشة الجوال</SelectItem></SelectContent></Select></div>;
}
export function CreateProject() {
  const [open, setOpen] = React.useState(false); const [name, setName] = React.useState(''); const [error, setError] = React.useState(''); const [result, setResult] = React.useState('');
  return <div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus/>إنشاء مساحة</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>مساحة جديدة للفريق</DialogTitle><DialogDescription>اجمع العمل والملفات والقرارات في مكان واحد. هذه معاينة محلية.</DialogDescription></DialogHeader><form className="grid gap-5" onSubmit={e => { e.preventDefault(); if (!name.trim()) { setError('اكتب اسم المساحة للمتابعة.'); return; } setResult(`أُنشئت «${name}» في المعاينة`); setOpen(false); }}><TextField label="اسم المساحة" placeholder="مثل: فرص القطاع الصحي" value={name} onChange={e => { setName(e.target.value); setError(''); }} error={error}/><RegionSelect id="dialog-region"/><div className="flex flex-wrap gap-2"><ProjectMenu label="خيارات المساحة" onChoose={setResult}/></div><DialogFooter><DialogClose asChild><Button variant="outline">إلغاء</Button></DialogClose><Button type="submit">إنشاء المساحة</Button></DialogFooter></form></DialogContent></Dialog><p role="status" className="tt-feedback">{result}</p></div>;
}
export function OverlayExamples() {
  const [result, setResult] = React.useState('');
  return <div className="grid gap-5"><div className="flex flex-wrap items-start gap-3"><CreateProject/><ProjectMenu onChoose={setResult}/><Popover><PopoverTrigger asChild><Button variant="outline"><SlidersHorizontal/>خيارات العرض</Button></PopoverTrigger><PopoverContent align="start"><div className="grid gap-4"><h3 className="font-semibold">خيارات العرض</h3><p className="text-sm text-muted-foreground">تفضيلات هذه المعاينة فقط.</p><div className="flex items-center justify-between gap-4"><Label htmlFor="compact-view">إظهار التفاصيل</Label><Switch id="compact-view" defaultChecked/></div></div></PopoverContent></Popover><Sheet><SheetTrigger asChild><Button variant="outline">فتح الفلاتر</Button></SheetTrigger><SheetContent side="end"><SheetHeader><SheetTitle>تصفية النتائج</SheetTitle><SheetDescription>حدد المنطقة ونوع الفرصة.</SheetDescription></SheetHeader><div className="mt-6 grid gap-5"><RegionSelect id="sheet-region"/><TextField label="كلمة البحث" placeholder="ابحث في الفرص"/><ProjectMenu label="إجراءات الفلاتر" onChoose={setResult}/></div></SheetContent></Sheet><AlertDialog><AlertDialogTrigger asChild><Button variant="destructive">حذف المساحة</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>حذف هذه المساحة؟</AlertDialogTitle><AlertDialogDescription>في المنتج، يوضح هذا المكان ما سيُحذف وإمكانية التراجع. هذه معاينة لا تحذف بيانات.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>إبقاء المساحة</AlertDialogCancel><AlertDialogAction onClick={() => setResult('اكتمل مثال التأكيد دون حذف بيانات')}>تأكيد المثال</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div><p role="status" className="tt-feedback">{result}</p></div>;
}
export function FormExamples() {
  return <div className="grid gap-6"><div className="grid gap-5 sm:grid-cols-2"><TextField label="اسم المشروع" placeholder="اكتب اسمًا واضحًا" hint="اسم يساعد الفريق على معرفة الهدف."/><TextField label="البريد الإلكتروني" type="email" dir="ltr" defaultValue="name@" error="أدخل بريدًا إلكترونيًا كاملًا."/><RegionSelect id="form-region"/><TextField label="رقم المرجع" dir="ltr" defaultValue="TT-2026-0148" readOnly hint="يُعرض المرجع باتجاهه الأصلي."/></div><div className="tt-field"><Label htmlFor="notes">ملاحظات الفريق</Label><Textarea id="notes" placeholder="ما الذي يحتاج الفريق معرفته؟"/></div><div className="flex flex-wrap gap-6"><div className="flex items-center gap-3"><Checkbox id="notify" defaultChecked/><Label htmlFor="notify">إرسال تنبيه عند اكتمال العمل</Label></div><div className="flex items-center gap-3"><Switch id="auto" defaultChecked/><Label htmlFor="auto">حفظ تلقائي</Label></div></div></div>;
}
export function ButtonExamples() {
  return <div className="grid gap-5"><div className="flex flex-wrap gap-3"><Button>حفظ التغييرات</Button><Button variant="secondary">إجراء ثانوي</Button><Button variant="outline"><Download/>تنزيل الملف</Button><Button variant="ghost">عرض التفاصيل<ArrowUpLeft className="ltr:rotate-90"/></Button><Button variant="destructive">حذف</Button></div><div className="flex flex-wrap gap-3"><Button disabled>غير متاح</Button><Button loading>جارٍ الحفظ…</Button><TooltipProvider><Tooltip><TooltipTrigger asChild><Button variant="outline" size="icon" aria-label="بحث"><Search/></Button></TooltipTrigger><TooltipContent>البحث في مساحة العمل</TooltipContent></Tooltip></TooltipProvider></div></div>;
}
export function NavigationExamples() {
  return <div className="grid gap-6"><Tabs defaultValue="overview"><TabsList aria-label="معلومات المشروع"><TabsTrigger value="overview">نظرة عامة</TabsTrigger><TabsTrigger value="files">الملفات</TabsTrigger><TabsTrigger value="team">الفريق</TabsTrigger></TabsList><TabsContent value="overview">ملخص يساعدك على اتخاذ الخطوة التالية.</TabsContent><TabsContent value="files">تظهر هنا ملفات المشروع بعد إضافتها.</TabsContent><TabsContent value="team">أعضاء الفريق وصلاحياتهم.</TabsContent></Tabs><Accordion type="single" collapsible><AccordionItem value="details"><AccordionTrigger>كيف نعرض التفاصيل الإضافية؟</AccordionTrigger><AccordionContent>تظل المعلومات الثانوية قريبة، وتظهر عند الحاجة دون أن تزاحم القرار الأساسي.</AccordionContent></AccordionItem></Accordion></div>;
}
export const sampleRows = [
  { id: '01', title: 'تطوير منصة لخدمات المستفيدين', category: 'تطوير برمجيات', status: 'جاهز للمراجعة', tone: 'success' as const, date: '١٢ سبتمبر' },
  { id: '02', title: 'تشغيل وصيانة الأنظمة الرقمية', category: 'خدمات تقنية', status: 'قيد الدراسة', tone: 'warning' as const, date: '١٥ سبتمبر' },
  { id: '03', title: 'تحليل البيانات ودعم القرار', category: 'ذكاء اصطناعي', status: 'مسوّدة', tone: 'neutral' as const, date: '١٨ سبتمبر' }
];
export function TableExample() {
  return <DataTable caption="فرص الفريق — بيانات توضيحية" rows={sampleRows} rowKey={r => r.id} columns={[{ key: 'title', heading: 'الفرصة', render: r => <span className="font-medium">{r.title}</span> }, { key: 'category', heading: 'المجال', render: r => r.category }, { key: 'status', heading: 'الحالة', render: r => <StatusBadge tone={r.tone}>{r.status}</StatusBadge> }, { key: 'date', heading: 'الموعد', render: r => <span className="whitespace-nowrap">{r.date}</span> }]} />;
}
export function StateExamples() {
  const [state, setState] = React.useState('empty');
  return <Tabs value={state} onValueChange={setState}><TabsList aria-label="حالة المحتوى"><TabsTrigger value="empty">فارغ</TabsTrigger><TabsTrigger value="loading">تحميل</TabsTrigger><TabsTrigger value="error">خطأ</TabsTrigger><TabsTrigger value="ready">مكتمل</TabsTrigger></TabsList><TabsContent value="empty"><EmptyState title="مساحتك جاهزة لأول فرصة" description="أضف فرصة لتبدأ تنظيم العمل مع فريقك." action={<Button onClick={() => setState('ready')}><Plus/>إضافة فرصة تجريبية</Button>}/></TabsContent><TabsContent value="loading"><LoadingState/></TabsContent><TabsContent value="error"><ErrorState description="لم نتمكن من جلب البيانات. بياناتك المحفوظة لم تتغيّر." action={<Button variant="outline" onClick={() => setState('ready')}>إعادة المحاولة</Button>}/></TabsContent><TabsContent value="ready"><TableExample/></TabsContent></Tabs>;
}
export function CardExample() {
 return <Card><CardHeader><CardTitle>العمل التالي واضح</CardTitle><CardDescription>بطاقة تجمع السياق والإجراء دون ازدحام.</CardDescription></CardHeader><CardContent><StatusBadge tone="success">جاهز للمراجعة</StatusBadge></CardContent></Card>;
}
