import * as React from 'react';
import { ArrowUpLeft, Blocks, Check, CheckCheck, CircleHelp, Code2, Compass, Download, LayoutDashboard, Layers3, Moon, Palette, PanelRight, Sun, Type, WandSparkles } from 'lucide-react';
import { AppShell, BrandMark, Button, StatusBadge, ThemeProvider, type DesignDirection, type DesignTheme, Tabs, TabsList, TabsTrigger, TabsContent, DetailPage, SettingsPage, PageHeader, PageSection, TextField } from '@toptech/ui';
import { ButtonExamples, FormExamples, NavigationExamples, OverlayExamples, StateExamples, TableExample, CreateProject } from '../src/stories/examples';

const sections = [
  { href: '#overview', label: 'نظرة على الهوية', icon: <Compass size={19}/> },
  { href: '#foundations', label: 'الأسس البصرية', icon: <Palette size={19}/> },
  { href: '#components', label: 'المكوّنات', icon: <Blocks size={19}/> },
  { href: '#patterns', label: 'قوالب المنتجات', icon: <PanelRight size={19}/> },
  { href: '#guidelines', label: 'دليل الاستخدام', icon: <CircleHelp size={19}/> }
];
export function SectionHeading({ number, title, description }: { number: string; title: string; description: string }) {
  return <div className="g-section-heading"><span className="g-eyebrow">{number} / قمم للتصميم</span><h1>{title}</h1><p>{description}</p></div>;
}
function Block({ title, note, children }: { title: string; note?: string; children: React.ReactNode }) {
  return <section className="g-block"><div className="g-block-head"><h2>{title}</h2>{note && <span>{note}</span>}</div><div className="g-block-body">{children}</div></section>;
}
export function Overview({ navigate }: { navigate: (href: string) => void }) {
  return <><section className="g-hero"><div className="g-hero-copy"><span className="g-eyebrow"><span className="g-live-dot"/>نظام هوية قمم التقنية · الإصدار الأول</span><h1>وضوحٌ يقود<br/>العمل<span className="g-blue">.</span></h1><p>لغة واحدة لمنتجاتنا.<br/>مساحة للتركيز، وتفاصيل تستحق الثقة.</p><div className="g-hero-actions"><Button onClick={() => navigate('#components')}>استكشف المكوّنات<ArrowUpLeft className="ltr:rotate-90"/></Button><Button variant="ghost" onClick={() => navigate('#guidelines')}>دليل البناء</Button></div><div className="g-hero-meta"><span>عربية أولًا</span><i/><span>فاتح وداكن</span><i/><span>من الجوال إلى المكتب</span></div></div><div className="g-signature" aria-label="نموذج العلامة"><div className="g-signature-grid"/><div className="g-signature-top"><span lang="en" dir="ltr">TOPTECH / DESIGN</span><span>01</span></div><BrandMark width={116} height={116}/><div className="g-signature-bottom"><span>قمم التقنية</span><small>أدوات ذكية. عمل واضح.</small></div></div></section>
  <div className="g-principles"><article><span>01</span><h2>القرار في المقدّمة</h2><p>إجراء رئيسي واضح، وما يدعمه قريب منه.</p></article><article><span>02</span><h2>اللون له وظيفة</h2><p>محايد للمساحة، أزرق للفعل، ودلالات للحالة.</p></article><article><span>03</span><h2>الثبات يصنع الثقة</h2><p>السلوك نفسه أينما انتقلت داخل المنتج.</p></article></div>
  <div className="g-overview-grid"><Block title="لغة اللون" note="دفءٌ محسوب"><div className="g-palette"><div style={{background:'#FAF9F5',color:'#2B2A27'}}><span>مساحة</span><small>#FAF9F5</small></div><div style={{background:'#2B2A27',color:'#FAF9F5'}}><span>حبر</span><small>#2B2A27</small></div><div style={{background:'hsl(225 80% 49%)',color:'#fff'}}><span>فعل</span><small>أزرق قمم</small></div><div style={{background:'#E6E4DB',color:'#2B2A27'}}><span>حدود</span><small>#E6E4DB</small></div></div></Block><Block title="صوتٌ واضح" note="IBM Plex Sans Arabic"><div className="g-type-specimen"><span className="g-type-aa">أبج<span>Aa</span></span><p>التقنية الجيّدة تجعل الخطوة التالية أوضح.</p><span className="g-type-digits">٠١٢٣٤٥٦٧٨٩ <bdi>0123456789</bdi></span></div></Block></div>
  <Block title="تفاصيل من النظام" note="مكوّنات حقيقية قابلة للتجربة"><div className="g-preview-row"><div><StatusBadge tone="success">جاهز للمراجعة</StatusBadge><h3>مساحة عمل للفريق</h3><p>كل ما تحتاجه للخطوة التالية.</p></div><CreateProject/></div></Block></>;
}
export function Foundations() {
  return <><SectionHeading number="02" title="الأسس البصرية" description="قرارات قليلة وواضحة تتكرّر باتساق في كل منتج."/>
    <Block title="العلامة" note="نظام قمم — مقترح العلامة للإصدار الأول"><div className="g-brand-sheet"><div><BrandMark width={72} height={72}/><strong>قمم التقنية</strong><span lang="en" dir="ltr">TOPTECH</span></div><div className="g-brand-reverse"><BrandMark width={72} height={72} style={{'--tt-mark-cutout':'#2B2A27'} as React.CSSProperties}/><strong>قمم التقنية</strong><span lang="en" dir="ltr">TOPTECH</span></div></div><p className="g-note">علامة هندسية بقمتين متداخلتين. مساحة الأمان ربع عرض العلامة، وأصغر استخدام 24 بكسل. استخدم النسخة الأحادية على الأرضيات المصوّرة.</p><div className="flex flex-wrap gap-2 mt-4"><Button asChild variant="outline"><a href="brand/mark.svg" download><Download/>العلامة SVG</a></Button><Button asChild variant="outline"><a href="brand/wordmark.svg" download><Download/>التوقيع الكامل</a></Button><Button asChild variant="outline"><a href="brand/mark-reverse.svg" download><Download/>النسخة المعكوسة</a></Button></div></Block>
    <Block title="ألوان بمعنى" note="تتغيّر القيم، وتبقى الدلالة"><div className="g-token-grid">{[['background','مساحة الصفحة'],['card','سطح المحتوى'],['foreground','النص الأساسي'],['primary','الإجراء الأساسي'],['muted','محتوى ثانوي'],['border','فاصل وحدود']].map(([token,label]) => <div key={token}><div className="g-token-swatch" style={{background:`hsl(var(--${token}))`}}/><strong>{label}</strong><code dir="ltr">{token}</code></div>)}</div><div className="flex flex-wrap gap-3 mt-6"><StatusBadge tone="success">اكتمل العمل</StatusBadge><StatusBadge tone="warning">يحتاج مراجعة</StatusBadge><StatusBadge tone="danger">تعذّر التنفيذ</StatusBadge><StatusBadge>غير معروف</StatusBadge></div><p className="g-note">الحالة تُقرأ بالنص والأيقونة مع اللون. «غير معروف» لا تتحول إلى صفر.</p></Block>
    <Block title="الخط والإيقاع" note="مقياس قابل للتكبير"><div className="g-type-scale"><div><span>عرض · 56</span><strong className="g-display">الوضوح يصنع الفرق.</strong></div><div><span>عنوان صفحة · 36</span><strong style={{fontSize:'2.25rem'}}>فرص تستحق اهتمامك</strong></div><div><span>عنوان قسم · 24</span><strong style={{fontSize:'1.5rem'}}>كل ما يحتاجه الفريق</strong></div><div><span>نص · 16</span><p>نشرح المعلومة بقدر ما يحتاجه القرار، ونترك للمحتوى مساحة للتنفّس.</p></div><div><span>تسمية · 14</span><p style={{fontSize:'.875rem'}}>آخر تحديث قبل دقيقتين</p></div></div></Block>
    <Block title="المسافات والزوايا" note="وحدة أساس 4 بكسل"><div className="g-spacing">{[4,8,12,16,24,32,48].map(n => <div key={n}><div style={{width:n,height:n}}/><span>{n}</span></div>)}</div><p className="g-note">حقول بارتفاع 44 بكسل، أسطح بزوايا 12 بكسل، وفراغ 24 بكسل بين مجموعات العمل. الحركة قصيرة وتحترم تقليل الحركة.</p></Block>
  </>;
}
export function Components() {
 return <><SectionHeading number="03" title="مكوّنات تتصرّف باتساق" description="جرّب النقر ولوحة المفاتيح. كل مثال يستخدم الحزمة التي ستدخل المنتجات."/><Block title="الأزرار والإجراءات" note="أساسي · ثانوي · خطر · انتظار"><ButtonExamples/></Block><Block title="القوائم والنوافذ" note="جرّب قائمة داخل نافذة"><OverlayExamples/></Block><Block title="الحقول والنماذج" note="تسمية · مساعدة · خطأ"><FormExamples/></Block><Block title="التنقّل داخل المحتوى"><NavigationExamples/></Block><Block title="حالات البيانات" note="فارغ · تحميل · خطأ · مكتمل"><StateExamples/></Block></>;
}
function SettingsTemplate() {
 const [saved,setSaved]=React.useState(false);
 return <form onSubmit={e=>{e.preventDefault();setSaved(true);}}><SettingsPage header={<PageHeader title="إعدادات مساحة العمل" description="نموذج محلي لتفضيلات الفريق."/>} footer={<><span role="status">{saved?'حُفظت التفضيلات في المعاينة':''}</span><Button type="submit">حفظ التغييرات</Button></>}><PageSection title="معلومات الفريق"><div className="grid gap-5"><TextField label="اسم الفريق" defaultValue="فريق قمم"/><TextField label="بريد التواصل" type="email" dir="ltr" defaultValue="team@example.com"/></div></PageSection></SettingsPage></form>;
}
export function Patterns() {
 return <><SectionHeading number="04" title="أساس لكل منتج" description="قوالب تنظم العمل، وتترك تفاصيل المجال للمنتج."/><Tabs defaultValue="list"><TabsList aria-label="قالب المنتج"><TabsTrigger value="list">قائمة</TabsTrigger><TabsTrigger value="details">تفاصيل</TabsTrigger><TabsTrigger value="settings">إعدادات</TabsTrigger></TabsList><TabsContent value="list"><section className="g-workspace"><div className="g-workspace-head"><div><span className="g-eyebrow">نموذج توضيحي / مساحة فريق</span><h2>صباح الخير، فريق قمم</h2><p>ثلاث فرص تنتظر خطوتكم التالية.</p></div><CreateProject/></div><div className="g-workspace-stats"><div><span>فرص قيد الدراسة</span><strong>٣</strong><small>في هذه المعاينة</small></div><div><span>جاهزة للمراجعة</span><strong>١</strong><StatusBadge tone="success">الخطوة التالية واضحة</StatusBadge></div><div><span>أقرب موعد</span><strong>١٢ <em>سبتمبر</em></strong><small>بيانات توضيحية</small></div></div><TableExample/></section></TabsContent><TabsContent value="details"><DetailPage header={<PageHeader eyebrow="فرص الفريق" title="تطوير منصة لخدمات المستفيدين" description="نموذج لتوزيع معلومات الفرصة والقرار." actions={<CreateProject/>}/>} summary={<StatusBadge tone="success">جاهز للمراجعة</StatusBadge>} aside={<PageSection title="الخطوة التالية"><p>راجع المتطلبات وحدد مسؤول المتابعة.</p></PageSection>}><PageSection title="ملخص الفرصة"><p>المعلومات الأساسية أولاً، والتفاصيل الإضافية في تبويبات واضحة.</p><NavigationExamples/></PageSection></DetailPage></TabsContent><TabsContent value="settings"><SettingsTemplate/></TabsContent></Tabs><div className="g-pattern-grid"><article><LayoutDashboard/><h3>صفحة قائمة</h3><p>عنوان وإجراء رئيسي، ثم بحث وقيود ونتائج. التمرير الأفقي يبقى داخل الجدول.</p></article><article><Layers3/><h3>صفحة تفاصيل</h3><p>ملخص قرار في الأعلى، وتبويبات للمحتوى. التفاصيل الإضافية تظهر عند الحاجة.</p></article><article><PanelRight/><h3>هيكل التطبيق</h3><p>تنقّل ثابت على المكتب، سكّة في العرض المتوسط، ودرج على الجوال.</p></article></div><Block title="كيف نستخدم هيكل التطبيق؟"><p className="g-note">هذا المعرض نفسه يستخدم AppShell من الحزمة. جرّب زر الطيّ، ثم صغّر الشاشة وافتح الدرج واختر وجهة. الحالة النشطة والإغلاق يتبعان الوجهة.</p></Block></>;
}
export function Guidelines() {
 const steps=[['حدد القرار','ما الذي يحتاج المستخدم معرفته أو فعله في هذه الشاشة؟'],['اختر القالب','قائمة أو تفاصيل أو إعدادات، ثم المكوّنات المعتمدة.'],['أكمل الحالات','تحميل وفراغ وخطأ ونجاح، مع العربية والجوال.'],['راجع المخرَج','قارن الشكل والسلوك والأداء قبل اعتماد التغيير.']];
 return <><SectionHeading number="05" title="دليل البناء" description="من فكرة جديدة إلى شاشة تنتمي للمنتج."/><div className="g-workflow">{steps.map(([title,description],i)=><article key={title}><span>0{i+1}</span><h2>{title}</h2><p>{description}</p></article>)}</div><Block title="صوت قمم" note="مباشر · هادئ · محدد"><div className="g-voice"><div><CheckCheck/><h3>نقول ما حدث وما يمكن فعله</h3><p>«تعذّر حفظ التغييرات. أعد المحاولة.»</p><p>«حُفظ المشروع. يمكنك مشاركته مع الفريق.»</p></div><div><Type/><h3>نسمّي الفعل بدقّة</h3><p>«إنشاء مساحة» · «تنزيل التقرير» · «إعادة المحاولة»</p><p>التسميات القصيرة تشرح النتيجة المتوقعة.</p></div></div></Block><Block title="للعمل مع وكيل AI" note="المكوّن المعتمد هو المرجع"><div className="g-prompt"><WandSparkles/><p>ابنِ الشاشة باستخدام <bdi>@toptech/ui</bdi> وقالب القائمة. استخدم رموز الهوية، وأكمل حالات البيانات. إذا احتجت سلوكًا جديدًا، أضفه للمكتبة مع فحصه قبل استخدامه في المنتج.</p></div></Block><Block title="عقد الجودة"><ul className="g-checklist">{['العنصر قابل للاستخدام باللمس ولوحة المفاتيح.','القائمة تظل داخل الشاشة حتى عندما تفتح داخل نافذة.','Escape يغلق الطبقة العليا ويعيد التركيز.','النص العربي الطويل لا يوسّع الصفحة.','اللون يرافق المعنى، ولا يحمله وحده.','تُراجع صور الفاتح والداكن والجوال قبل تحديث المراجع.','أي تراجع للأداء يُقاس على البناء النهائي.'].map(item => <li key={item}><Check size={18}/>{item}</li>)}</ul></Block><div className="g-endnote"><Code2/><p>المصدر: <bdi>design-system</bdi> · التوثيق التفصيلي في <bdi>README.md</bdi> · أمثلة المكوّنات في Storybook.</p></div></>;
}
export function Gallery() {
 const params = new URLSearchParams(window.location.search);
 const [theme,setTheme] = React.useState<DesignTheme>(params.get('theme') === 'dark' ? 'dark': params.get('theme') === 'auto' ? 'auto' : 'light');
 const [dir,setDir] = React.useState<DesignDirection>(params.get('dir') === 'ltr' ? 'ltr':'rtl');
 const [active,setActive] = React.useState(sections.some(s=>s.href===window.location.hash) ? window.location.hash : '#overview');
 React.useEffect(()=>{ const sync=()=>setActive(sections.some(s=>s.href===window.location.hash) ? window.location.hash : '#overview'); window.addEventListener('hashchange',sync); return ()=>window.removeEventListener('hashchange',sync); },[]);
 function navigate(href:string){window.location.hash=href; setActive(href); window.scrollTo({top:0,behavior:'instant'});}
 return <ThemeProvider theme={theme} dir={dir}><AppShell items={sections} activeHref={active} onNavigate={navigate} header={<div className="g-header-tools"><span className="g-release">نظام التصميم <bdi>0.1</bdi></span><Button variant="ghost" size="icon" aria-label={theme==='light'?'تفعيل المظهر الداكن':'تفعيل المظهر الفاتح'} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon/>:<Sun/>}</Button><Button variant="outline" className="g-dir-button" aria-label="تبديل اتجاه الواجهة" onClick={()=>setDir(dir==='rtl'?'ltr':'rtl')}>{dir==='rtl'?'LTR':'RTL'}</Button></div>}><div className="g-container">{active==='#overview'?<Overview navigate={navigate}/>:active==='#foundations'?<Foundations/>:active==='#components'?<Components/>:active==='#patterns'?<Patterns/>:<Guidelines/>}<footer className="g-footer"><span>قمم التقنية</span><span>مرجع حيّ لبناء منتجاتنا</span><bdi>DESIGN / 01</bdi></footer></div></AppShell></ThemeProvider>;
}
